//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmosystemWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int Cuenta_id { get; set; }
        public System.DateTime Cuenta_FechaProceso { get; set; }
        public int Cuenta_Valor { get; set; }
        public int Cuenta_CodigoContable { get; set; }
        public string Cuenta_Estado { get; set; }
        public System.DateTime Cuenta_FechaIngreso { get; set; }
        public int Etapa_id { get; set; }
        public int Plan_Id { get; set; }
    
        public virtual Etapa Etapa { get; set; }
        public virtual PlandeCuentas PlandeCuentas { get; set; }
    }
}
