//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmosystemWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etapa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etapa()
        {
            this.Cuenta = new HashSet<Cuenta>();
        }
    
        public int Etapa_id { get; set; }
        public string Etapa_name { get; set; }
        public string Etapa_tipo { get; set; }
        public System.DateTime Etapa_inicioCons { get; set; }
        public System.DateTime Etapa_terminoCons { get; set; }
        public System.DateTime Etapa_inicioVenta { get; set; }
        public System.DateTime Etapa_terminoVenta { get; set; }
        public int Etapa_codigoContable { get; set; }
        public int Etapa_unidades { get; set; }
        public int Proy_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuenta { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
