//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmosystemWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InmosysytemDBEntities4 : DbContext
    {
        public InmosysytemDBEntities4()
            : base("name=InmosysytemDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Etapa> Etapa { get; set; }
        public virtual DbSet<Inmobiliaria> Inmobiliaria { get; set; }
        public virtual DbSet<PlandeCuentas> PlandeCuentas { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
    
        public virtual int cuentaspivot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cuentaspivot");
        }
    }
}
