//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmosystemWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Etapa = new HashSet<Etapa>();
        }
    
        public int Proy_id { get; set; }
        public string Proy_name { get; set; }
        public string Proy_zona { get; set; }
        public string Proy_region { get; set; }
        public string Proy_ciudad { get; set; }
        public string Proy_calle { get; set; }
        public string Proy_gerente { get; set; }
        public string Proy_descripcion { get; set; }
        public int Proy_codigoContable { get; set; }
        public int Inmo_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etapa> Etapa { get; set; }
        public virtual Inmobiliaria Inmobiliaria { get; set; }
    }
}
